export const ERP_COLUMNS = [
  "SUPPLIER", "BILL NO.", "DATE", "COMPANY", "CODE", "BARCODE", 
  "ITEM NAME", "PACK", "BATCH", "EXPIRY", "QTY", "F.QTY", 
  "HALFP", "FTRATE", "SRATE", "MRP", "DIS", "EXCISE", 
  "VAT", "ADNLVAT", "AMOUNT", "LOCALCENT", "SCM1", "SCM2", 
  "SCMPER", "HSNCODE", "CGST", "SGST", "IGST", "PSRLNO", 
  "TCSPER", "TCSAMT", "ALTERCODE", "PONUMBER"
];

export const HEADER_KEYWORDS = [
  "ITEM NAME", "ITEM", "PRODUCT", "DESCRIPTION", "PARTICULARS", "DRUG NAME", 
  "MEDICINE", "NAME OF ITEM", "BRAND", "QTY", "QUANTITY", "BATCH", "EXPIRY", 
  "PACK", "PACKING", "MRP", "RATE", "PTR", "AMOUNT", "HSN", "CGST", "SGST", "IGST"
];

export const HEADER_SYNONYMS: Record<string, string[]> = {
  "ITEM NAME": [
    "ITEM", "ITEM NAME", "PRODUCT", "PRODUCT NAME", "PARTICULARS", 
    "DESCRIPTION", "DESCRIPTION OF GOODS", "DRUG NAME", "MEDICINE", 
    "MEDICINE NAME", "NAME OF ITEM", "NAME OF PRODUCT", "ITEMS", 
    "PRODUCT DESCRIPTION", "PARTICULAR", "BRAND", "BRAND NAME", "ITEM DESCRIPTION"
  ],
  "PACK": ["PACK", "PACKING", "PKG", "PACK SIZE", "UNIT", "BOX", "STRIP", "UOM", "PACKING SIZE"],
  "BATCH": ["BATCH", "BATCH NO", "BATCH NO.", "BATCH/LOT", "B.NO", "B.NO.", "LOT", "LOT NO", "LOT/BATCH", "BTCH"],
  "EXPIRY": ["EXPIRY", "EXP", "EXP.", "EXP DATE", "EXP.DATE", "MFG/EXP", "E.DATE", "EXP DATE/MFG", "EXP DT", "EXP-DATE", "EXPDATE"],
  "QTY": ["QTY", "QUANTITY", "QTY.", "NOS", "QNTY", "BILLED QTY", "BILL QTY", "P.QTY"],
  "F.QTY": ["F.QTY", "FREE QTY", "FREE", "FREE NOS", "BONUS", "SCHEME QTY", "F QTY", "FREE QTY."],
  "SRATE": ["SRATE", "S.RATE", "RATE", "PTR", "P.RATE", "PUR RATE", "PURCHASE RATE", "UNIT PRICE", "RATE (RS)", "PRICE", "NET RATE", "S RATE"],
  "MRP": ["MRP", "M.R.P.", "M.R.P", "MRP (RS)", "MAX RETAIL PRICE", "R.P.", "M.R.P (RS)"],
  "DIS": ["DIS", "DISC", "DISC%", "DIS %", "DISCOUNT", "LESS", "DISC AMT", "DISC.", "DIS%"],
  "AMOUNT": ["AMOUNT", "NET AMOUNT", "TOTAL", "TOTAL AMOUNT", "VALUE", "AMT", "NET AMT", "TAXABLE VALUE", "TOTAL AMT"],
  "HSNCODE": ["HSNCODE", "HSN", "HSN/SAC", "HSN CODE", "SAC CODE", "HSN/SAC CODE", "HSN CODE."],
  "CGST": ["CGST", "CGST%", "CGST RATE", "CGST AMT", "C-GST", "CGST %"],
  "SGST": ["SGST", "SGST%", "SGST RATE", "SGST AMT", "S-GST", "UTGST", "SGST %"],
  "IGST": ["IGST", "IGST%", "IGST RATE", "IGST AMT", "I-GST", "IGST %"],
  "COMPANY": ["COMPANY", "MFG", "MFR", "MANUFACTURER", "BRAND", "CO.", "MAKER", "MFG CO", "MFR NAME", "MFG."]
};
